Add back outline offset
Q42/floating-focus-a11y pull request #33
Opened 2020-11-17 17:25 UTC by Jirinrin

Another lil' bugfix. It seems in all the chaos of #28 a thing got lost, and that thing was changing the padding of the floater based on the focused element's style!
So this adds that back.

2020-11-18 23:52 UTC, Jirinrin commented on package-lock.json
> +  "version": "1.3.2",
Oops, this got in here because I accidentally pulled master... haha

2020-11-19 08:30 UTC, guidobouman requested changes

2020-11-19 08:30 UTC, guidobouman commented on src/floating-focus.js
> +			padding,
Taken care of by getFloaterPosition at https://github.com/Q42/floating-focus-a11y/pull/33/files#diff-062ca1e52889c97e83903d264a9b1d5e5392c906ae21b2aaeb25afebd7b29113R193

2020-11-19 08:30 UTC, closed without merging

2020-11-19 08:34 UTC, guidobouman commented
@Jirinrin Or did I miss something?